module.exports = {
    version: "0.1",
    words: [
        "barline",
        "barlines",
        "Bézier",
        "BFSL",
        "Bilby",
        "evented",
        "frontfield",
        "measurenb",
        "multiselection",
        "pagewidth",
        "Rcoords",
        "ritardandos",
        "sonner",
        "spms",
        "Topbar",
        "Tribbiani",
        "Uncurried",
        "Vree",
        "Zingali",
    ],
    ignorePaths: ["node_modules/**", "dist/**", "build/**", "src/assets"],
    ignoreRegExpList: ["@[a-z\\-]+", "\\(#.*\\)"],
};
