module.exports = {
    version: "0.1",
    words: [
        "autoincrement",
        "openmarch",
        "barline",
        "barlines",
        "Bézier",
        "BFSL",
        "Bilby",
        "customizer",
        "dbstat",
        "evented",
        "frontfield",
        "fieldots",
        "measurenb",
        "musicxml",
        "multiselection",
        "notarytool",
        "pagewidth",
        "Rcoords",
        "ritardandos",
        "rootfile",
        "sonner",
        "spms",
        "Titlebar",
        "togglefullscreen",
        "Topbar",
        "trackpad",
        "trackpads",
        "Trackpad",
        "Trackpads",
        "Tribbiani",
        "Uncurried",
        "unmaximize",
        "viewbox",
        "Vree",
        "wavesurfer",
        "Zingali",
    ],
    ignorePaths: ["node_modules/**", "dist/**", "build/**", "src/assets"],
    ignoreRegExpList: ["@[a-z\\-]+", "\\(#.*\\)"],
};
