packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - canvas
  - core-js
  - electron
  - esbuild
  - sharp
patchedDependencies:
  canvas: patches/canvas.patch
