packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@sentry/cli"
  - "@tailwindcss/oxide"
  - canvas
  - core-js
  - electron
  - esbuild
  - libsql
  - "@libsql/client"
  - sharp
patchedDependencies:
  canvas: patches/canvas.patch
