import { describe, it, expect } from "vitest";
import { dryRunImportPdfCoordinates } from "@/importers/pdfCoordinates";

// Minimal integration: feed a tiny synthetic PDF generated by pdfjs? Not feasible in unit; instead simulate by reusing parsePage contract.
// This is a placeholder ensuring the importer function exists and returns the expected shape when given an empty buffer (should throw).

describe("importer integration", () => {
    it("exposes dryRunImportPdfCoordinates and rejects invalid data", async () => {
        await expect(
            dryRunImportPdfCoordinates(new ArrayBuffer(0), {
                xCheckpoints: [],
                yCheckpoints: [],
            } as any),
        ).rejects.toBeTruthy();
    });
});
