name: Bug Report
description: Something didn’t work the way you expected? Let us know here!
title: "[BUG]: "
labels: ["bug"]
type: bug

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file an OpenMarch bug report! Your feedback helps make OpenMarch better for everyone.

  - type: markdown
    attributes: 
      value: |
        If there is an existing bug report similar to the one you are about to create, please leave a thumbs up and comment on that report, rather than making a new one. 
        Be sure to add additional details if the additional if you think it would help!
        
  - type: checkboxes
    id: verified
    attributes:
      label: Report hasn't been filed before
      options:
        - label: I have verified that the bug I'm about to report hasn't been filed before
          required: true

  - type: input
    attributes:
      label: What version of OpenMarch are you using?
      description: You can find the version in the app settings or title bar
      placeholder: 0.0.0
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11 (x64)
        - Windows 11 (arm64)
        - Windows 10 (x64)
        - Windows 10 (arm64)
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (x64)
        - Linux (arm64)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please enter the following information -
        - What went wrong
        - What did you expect to happen
        - What steps could we take to reproduce the issue?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots, screen recordings, and dots
      description: If it helps show what went wrong, feel free to include a screenshot or recording (GIFs are great too!)

  - type: textarea
    id: dotsfile
    attributes:
      label: Upload you .dots file (optional)
      description: |
        Being able to debug with the file itself is very helpful

        Before uploading your `.dots` file here, change the extension to `.txt` so GitHub allows uploading.
