import Marcher from "@/global/classes/Marcher";
import Page from "@/global/classes/Page";
import {
    DatabaseMarcherPage,
    databaseMarcherPagesToMarcherPages,
} from "@/global/classes/MarcherPage";
import { FieldProperties } from "@openmarch/core";
import MarcherLine from "@/global/classes/canvasObjects/MarcherLine";
import FieldPropertiesTemplates from "@/global/classes/FieldProperties.templates";
import { marcherPageMapFromArray } from "@/global/classes/MarcherPageIndex";
import { DatabaseShape, DatabaseShapePage } from "@/db-functions";

export const mockMarchers: Marcher[] = [
    {
        id: 1,
        type: "marcher",
        name: "Marc Sylvester",
        section: "Flute",
        drill_prefix: "F",
        drill_order: 1,
        drill_number: "F1",
        notes: "Inducted in 2001 - DCI Hall of Fame (probably didn't play flute",
        year: "Freshman",
        created_at: "some_time",
        updated_at: "other_time",
    },
    {
        id: 2,
        type: "marcher",
        name: "George Zingali",
        section: "Snare",
        drill_prefix: "S",
        drill_order: 1,
        drill_number: "S1",
        notes: "Inducted in 1991 - DCI Hall of Fame",
        year: "Sophomore",
        created_at: "some_time",
        updated_at: "other_time",
    },
    {
        id: 3,
        type: "marcher",
        name: "John Bilby",
        section: "Trumpet",
        drill_prefix: "T",
        drill_order: 1,
        drill_number: "T1",
        notes: null,
        year: null,
        created_at: "some_time",
        updated_at: "other_time",
    },
    {
        id: 4,
        type: "marcher",
        name: "",
        section: "Baritone",
        drill_prefix: "B",
        drill_order: 2,
        drill_number: "B2",
        notes: null,
        year: null,
        created_at: "some_time",
        updated_at: "other_time",
    },
] as const;

export const mockPages: Page[] = [
    {
        id: 1,
        name: "1",
        counts: 16,
        order: 1,
        notes: "This is the first page",
        nextPageId: 2,
        previousPageId: null,
        isSubset: false,
        duration: 8,
        beats: [],
        measures: [],
        measureBeatToStartOn: 1,
        measureBeatToEndOn: 0,
        timestamp: 0,
    } satisfies Page,
    {
        id: 2,
        name: "2",
        counts: 8,
        order: 2,
        notes: "This is the second page",
        nextPageId: 3,
        previousPageId: 1,
        isSubset: false,
        duration: 4,
        beats: [],
        measures: [],
        measureBeatToStartOn: 1,
        measureBeatToEndOn: 0,
        timestamp: 8,
    } satisfies Page,
    {
        id: 3,
        name: "3",
        counts: 16,
        order: 3,
        notes: null,
        nextPageId: null,
        previousPageId: 2,
        isSubset: false,
        duration: 8,
        beats: [],
        measures: [],
        measureBeatToStartOn: 1,
        measureBeatToEndOn: 0,
        timestamp: 12,
    } satisfies Page,
] as const;

export const mockMarcherPages: Partial<DatabaseMarcherPage>[] = [
    {
        id: 1,
        marcher_id: 1,
        page_id: 1,
        x: 50,
        y: 50,
        notes: "This is the first marcherPage",
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
    {
        id: 2,
        marcher_id: 2,
        page_id: 1,
        x: 0,
        y: 0,
        notes: "This is the second marcherPage",
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
    {
        id: 3,
        marcher_id: 3,
        page_id: 1,
        x: -200,
        y: -500,
        notes: null,
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
    {
        id: 4,
        marcher_id: 1,
        page_id: 2,
        x: 0,
        y: 0,
        notes: "This is the first marcherPage",
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
    {
        id: 5,
        marcher_id: 2,
        page_id: 2,
        x: 284,
        y: 963.1,
        notes: "This is the second marcherPage",
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
    {
        id: 6,
        marcher_id: 3,
        page_id: 2,
        x: -200,
        y: 105.015,
        notes: null,
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
    {
        id: 1,
        marcher_id: 1,
        page_id: 3,
        x: 50,
        y: 50,
        notes: "This is the first marcherPage",
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
    {
        id: 2,
        marcher_id: 2,
        page_id: 3,
        x: 0,
        y: 0,
        notes: "This is the second marcherPage",
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
    {
        id: 3,
        marcher_id: 3,
        page_id: 3,
        x: -200,
        y: -500,
        notes: null,
        created_at: "some_time",
        updated_at: "other_time",
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        rotation_degrees: 0,
    },
] as const;

export const mockMarcherPageMap = marcherPageMapFromArray(
    databaseMarcherPagesToMarcherPages(
        mockMarcherPages as DatabaseMarcherPage[],
    ),
);

export const mockMarcherLines: MarcherLine[] = [
    new MarcherLine({
        id: 1,
        startPageId: 1,
        endPageId: 2,
        x1: 0,
        y1: 0,
        x2: 100,
        y2: 100,
        notes: "This is the first marcherLine",
    }),
    new MarcherLine({
        id: 2,
        startPageId: 2,
        endPageId: 2,
        x1: 200,
        y1: 0,
        x2: 0,
        y2: 0,
    }),
    new MarcherLine({
        id: 1,
        startPageId: 2,
        endPageId: 4,
        x1: 5,
        y1: 10,
        x2: -50,
        y2: 1000,
        notes: "This is the last marcherLine",
    }),
] as const;

export const mockShapes: DatabaseShape[] = [
    {
        id: 1,
        name: "Shape 1",
        updated_at: "some_time",
        created_at: "other_time",
        notes: "These are notes",
    },
    {
        id: 2,
        name: "Shape 2",
        updated_at: "some_time",
        created_at: "other_time",
        notes: null,
    },
    {
        id: 3,
        name: "Shape 3",
        updated_at: "some_time",
        created_at: "other_time",
        notes: "",
    },
] as const;

export const mockShapePages: DatabaseShapePage[] = [
    {
        id: 1,
        shape_id: 1,
        page_id: 1,
        svg_path: "M 0 0 L 100 100",
        created_at: "some_time",
        updated_at: "other_time",
        notes: "These are notes",
    },
    {
        id: 2,
        shape_id: 2,
        page_id: 1,
        svg_path: "M 200 0 L 0 0",
        created_at: "some_time",
        updated_at: "other_time",
        notes: null,
    },
    {
        id: 3,
        shape_id: 3,
        page_id: 1,
        svg_path: "M 5 10 L -50 1000",
        created_at: "some_time",
        updated_at: "other_time",
        notes: "",
    },
] as const;

/**
 * A list of properties for a college football field. Each property is in steps. For pixels, multiply by pixelsPerStep.
 */
export const mockNCAAFieldProperties: FieldProperties =
    FieldPropertiesTemplates.COLLEGE_FOOTBALL_FIELD_NO_END_ZONES;
/**
 * A mock to represent the field back when an 8-to-5 step was 24 pixels.
 * This is here because many of the unit tests had that number hard-coded
 */
export const legacyMockNCAAFieldProperties: FieldProperties =
    new FieldProperties({
        ...mockNCAAFieldProperties,
        stepSizeInches: 22.5,
    });
