import { clsx } from "clsx";

export const ProseClass = clsx(
    "prose",
    "w-full",
    "leading-loose",
    "text-text",
    "marker:text-text",
    "prose-headings:text-text",
    "prose-h1:text-h1",
    "prose-h2:text-h2",
    "prose-h3:text-h3",
    "prose-h4:text-h4",
    "prose-p:text-text",
    "prose-li:text-text",
    "prose-p:leading-loose",
    "prose-a:text-accent",
    "prose-a:underline",
    "prose-hr:border",
    "prose-hr:border-stroke",
    "prose-blockquote:text-text",
    "prose-blockqoute:border-black",
    "prose-strong:text-text",
    "prose-strong:font-semibold",
    "prose-em:italic",
    "prose-code:bg-fg-2",
    "prose-code:border prose-code:border-stroke",
    "prose-code:font-mono",
    "prose-code:text-[0.85rem]",
    "prose-code:text-text",
    "prose-code:rounded-8",
    "prose-code:p-4",
    "prose-code:before:content-none",
    "prose-code:after:content-none",
    "prose-ol:list-decimal",
    "prose-ul:list-disc",
    "prose-ul:list-black",
    "prose-li:pl-6",
    "prose-table:w-full",
    "prose-img:rounded-6",
    "prose-img:border",
    "prose-img:border-stroke",
    "prose-video:rounded-6",
    "prose-video:border",
    "prose-video:border-stroke",
);
