import Marcher from "@/global/classes/Marcher";
import Page from "@/global/classes/Page";
import MarcherPage from "@/global/classes/MarcherPage";
import { marcherPageMapFromArray } from "@/global/classes/MarcherPageIndex";
import { UiSettings } from "@/stores/UiSettingsStore";
import { marcherVisualsFromMarchers } from "@/global/classes/MarcherVisualGroup";
import { DEFAULT_FIELD_THEME } from "@openmarch/core";
/**
 * A separate mock file than global mocks since the canvas will likely be quite large and have many mocks.
 */

export const falsyUiSettings: UiSettings = {
    isPlaying: false,
    lockX: false,
    lockY: false,
    previousPaths: false,
    nextPaths: false,
    showCollisions: true,
    gridLines: false,
    halfLines: false,
    timelinePixelsPerSecond: 40,
    focussedComponent: "canvas",
    mouseSettings: {
        trackpadMode: true,
        trackpadPanSensitivity: 0.5,
        zoomSensitivity: 0.03,
        panSensitivity: 0.5,
    },
};

export const mockMarchers: Marcher[] = [
    new Marcher({
        id: 1,
        name: "Marc Sylvester",
        section: "Flute",
        drill_prefix: "F",
        drill_order: 1,
        notes: "Inducted in 2001 - DCI Hall of Fame (probably didn't play flute",
        year: "Freshman",
    }),
    new Marcher({
        id: 2,
        name: "George Zingali",
        section: "Snare",
        drill_prefix: "S",
        drill_order: 1,
        notes: "Inducted in 1991 - DCI Hall of Fame",
        year: "Sophomore",
    }),
    new Marcher({
        id: 3,
        name: "John Bilby",
        section: "Trumpet",
        drill_prefix: "T",
        drill_order: 1,
        notes: undefined,
        year: undefined,
    }),
    new Marcher({
        id: 4,
        name: "",
        section: "Baritone",
        drill_prefix: "B",
        drill_order: 2,
        notes: undefined,
        year: undefined,
    }),
] as const;

export const mockPages: Page[] = [
    {
        id: 1,
        name: "1",
        counts: 16,
        order: 1,
        notes: "This is the first page",
        nextPageId: 2,
        previousPageId: null,
        isSubset: false,
        duration: 8,
        beats: [],
        measures: [],
        measureBeatToStartOn: 1,
        measureBeatToEndOn: 0,
        timestamp: 0,
    } satisfies Page,
    {
        id: 2,
        name: "2",
        counts: 8,
        order: 2,
        notes: "This is the second page",
        nextPageId: 3,
        previousPageId: 1,
        isSubset: false,
        duration: 4,
        beats: [],
        measures: [],
        measureBeatToStartOn: 1,
        measureBeatToEndOn: 0,
        timestamp: 8,
    } satisfies Page,
    {
        id: 3,
        name: "3",
        counts: 16,
        order: 3,
        notes: null,
        nextPageId: null,
        previousPageId: 2,
        isSubset: false,
        duration: 8,
        beats: [],
        measures: [],
        measureBeatToStartOn: 1,
        measureBeatToEndOn: 0,
        timestamp: 12,
    } satisfies Page,
] as const;

export const mockMarcherPages: MarcherPage[] = [
    {
        id: 1,
        marcher_id: 1,
        page_id: 1,
        x: 50,
        y: 50,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: "This is the first marcherPage",
    },
    {
        id: 2,
        marcher_id: 2,
        page_id: 1,
        x: 0,
        y: 0,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: "This is the second marcherPage",
    },
    {
        id: 3,
        marcher_id: 3,
        page_id: 1,
        x: -200,
        y: -500,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: null,
    },
    {
        id: 4,
        marcher_id: 1,
        page_id: 2,
        x: 0,
        y: 0,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: "This is the first marcherPage",
    },
    {
        id: 5,
        marcher_id: 2,
        page_id: 2,
        x: 284,
        y: 963.1,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: "This is the second marcherPage",
    },
    {
        id: 6,
        marcher_id: 3,
        page_id: 2,
        x: -200,
        y: 105.015,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: null,
    },
    {
        id: 7,
        marcher_id: 1,
        page_id: 3,
        x: 50,
        y: 50,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: "This is the first marcherPage",
    },
    {
        id: 8,
        marcher_id: 2,
        page_id: 3,
        x: 0,
        y: 0,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: "This is the second marcherPage",
    },
    {
        id: 9,
        marcher_id: 3,
        page_id: 3,
        x: -200,
        y: -500,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: null,
    },
    {
        id: 10,
        marcher_id: 4,
        page_id: 1,
        x: -200,
        y: -500,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: null,
    },
    {
        id: 11,
        marcher_id: 4,
        page_id: 2,
        x: -200,
        y: -500,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: null,
    },
    {
        id: 12,
        marcher_id: 4,
        page_id: 3,
        x: -200,
        y: -500,
        path_data_id: null,
        path_start_position: null,
        path_end_position: null,
        notes: null,
    },
] as const;

export const mockMarcherPageMap = marcherPageMapFromArray(mockMarcherPages);
export const mockMarcherVisualMap = marcherVisualsFromMarchers({
    receivedMarchers: mockMarchers,
    fieldTheme: DEFAULT_FIELD_THEME,
});
