name: Build/release

on:
    push:
        branches: [test]

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Print version tag
              run: "echo 'Version tag: ${{ github.ref_name }}'"

            - name: Check if version tag is valid
              if: startsWith(github.ref_name, 'v')
              run: |
                  if [[ ! ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                  echo "Version tag is not valid. Exiting."
                  exit 1
