name: Build/release

on:
    push:
        branches: [test]

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Check for version tag
              if: ${{ startsWith(github.ref, 'refs/tags/v') }}
              run: echo "TAG NOT PROVIDED" && exit 1
