name: Build/release

on:
    push:
        branches: [test]

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Print version tag
              run: "echo 'Version tag: ${{ github.ref_name }}'"
